# The next line updates PATH for the Google Cloud SDK.
#
# NOTE: This code was generated by the Google Cloud SDK installer.
if [ -f '/Users/daveyarwood/google-cloud-sdk/path.fish.inc' ]
  . '/Users/daveyarwood/google-cloud-sdk/path.fish.inc'
end
