set shell=bash
set nocompatible
filetype off " required by Vundle

set runtimepath+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'gmarik/Vundle.vim'

" neovim-specific
Plugin 'neovim/node-host'

" aesthetic
Plugin 'altercation/vim-colors-solarized'
Plugin 'amix/vim-zenroom2'
Plugin 'flazz/vim-colorschemes'
Plugin 'gorodinskiy/vim-coloresque'
Plugin 'junegunn/goyo.vim'
Plugin 'ntpeters/vim-airline-colornum'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'

" editor enhancements
Plugin 'airblade/vim-gitgutter'
Plugin 'benmills/vimux'
Plugin 'christoomey/vim-tmux-navigator'
Plugin 'dyng/ctrlsf.vim'
Plugin 'godlygeek/tabular'
Plugin 'jiangmiao/auto-pairs'
Plugin 'junegunn/fzf.vim'
" TODO: switch to vim-plug and do this instead:
" Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
set rtp+=~/.fzf
Plugin 'majutsushi/tagbar'
Plugin 'ntpeters/vim-better-whitespace'
Plugin 'schickling/vim-bufonly'
Plugin 'scrooloose/syntastic'
Plugin 'Shougo/deoplete.nvim'
Plugin 'Shougo/unite.vim'
Plugin 'Shougo/vimfiler.vim'
Plugin 'szw/vim-ctrlspace'
Plugin 'tommcdo/vim-lion'
Plugin 'tpope/vim-commentary'
Plugin 'tpope/vim-endwise'
Plugin 'tpope/vim-repeat'
Plugin 'tpope/vim-surround'
Plugin 'tpope/vim-unimpaired'
Plugin 'tpope/vim-vinegar'
Plugin 'vim-scripts/gitignore'

" clojure things
Plugin 'clojure-vim/async-clj-omni'
Plugin 'guns/vim-clojure-static'
Plugin 'guns/vim-clojure-highlight'
Plugin 'guns/vim-sexp'
Plugin 'luochen1990/rainbow'
Plugin 'snoe/clj-refactor.nvim'
Plugin 'tpope/vim-classpath'
Plugin 'tpope/vim-dispatch'
Plugin 'tpope/vim-fireplace'
Plugin 'tpope/vim-projectionist'
Plugin 'tpope/vim-salve'
Plugin 'tpope/vim-sexp-mappings-for-regular-people'

" other languages/filetypes
Plugin 'adimit/prolog.vim'
Plugin 'andreimaxim/vim-io'
Plugin 'cespare/vim-toml'
Plugin 'chochos/ceylon-vim'
Plugin 'dag/vim-fish'
Plugin 'daveyarwood/vim-alda'
Plugin 'derekwyatt/vim-scala'
Plugin 'digitaltoad/vim-pug'
Plugin 'dleonard0/pony-vim-syntax'
Plugin 'dpwright/vim-tup'
Plugin 'elixir-lang/vim-elixir'
Plugin 'fatih/vim-go'
Plugin 'idris-hackers/idris-vim'
Plugin 'jtratner/vim-flavored-markdown'
Plugin 'JuliaEditorSupport/julia-vim'
Plugin 'junegunn/vader.vim'
Plugin 'kchmck/vim-coffee-script'
Plugin 'keith/swift.vim'
Plugin 'lambdatoast/elm.vim'
Plugin 'lfe/vim-lfe'
Plugin 'l04m33/vlime', {'rtp': 'vim/'}
Plugin 'mattn/emmet-vim'
Plugin 'matze/vim-lilypond'
Plugin 'OrangeT/vim-csharp'
Plugin 'PProvost/vim-ps1'
Plugin 'raichoo/purescript-vim'
Plugin 'rhysd/vim-crystal'
Plugin 'rust-lang/rust.vim'
Plugin 'stephencelis/vim-mml'
Plugin 'tfnico/vim-gradle'
Plugin 'tmux-plugins/vim-tmux'
Plugin 'udalov/kotlin-vim'
Plugin 'wlangstroth/vim-racket'

" misc
Plugin 'chrisbra/unicode.vim'
Plugin 'gregsexton/gitv'
Plugin 'itchyny/calendar.vim'
Plugin 'jreybert/vimagit'
Plugin 'mileszs/ack.vim'
Plugin 'szw/vim-dict'
Plugin 'terryma/vim-multiple-cursors'
Plugin 'tpope/vim-fugitive'
Plugin 'vimwiki/vimwiki'

call vundle#end()
filetype plugin indent on

" ultimate vimrc stuff
set runtimepath+=~/.vim_runtime

source ~/.vim_runtime/vimrcs/basic.vim
source ~/.vim_runtime/vimrcs/filetypes.vim
source ~/.vim_runtime/vimrcs/plugins_config.vim
source ~/.vim_runtime/vimrcs/extended.vim

try
source ~/.vim_runtime/my_configs.vim
catch
endtry
