set shell=bash
set nocompatible

call plug#begin('~/.vim/bundle')

" aesthetic
Plug 'altercation/vim-colors-solarized'
Plug 'amix/vim-zenroom2'
Plug 'flazz/vim-colorschemes'
Plug 'gorodinskiy/vim-coloresque'
Plug 'itchyny/lightline.vim'
Plug 'junegunn/goyo.vim'
Plug 'sonph/onehalf', {'rtp': 'vim/'}

" editor enhancements
Plug 'airblade/vim-gitgutter'
Plug 'benmills/vimux'
Plug 'christoomey/vim-tmux-navigator'
Plug 'dyng/ctrlsf.vim'
Plug 'Floobits/floobits-neovim', { 'do': ':UpdateRemotePlugins' }
Plug 'gerw/vim-HiLinkTrace'
Plug 'godlygeek/tabular'
Plug 'jiangmiao/auto-pairs'
Plug 'junegunn/fzf.vim'
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'kassio/neoterm'
Plug 'ludovicchabant/vim-gutentags'
Plug 'majutsushi/tagbar'
Plug 'neomake/neomake'
Plug 'ntpeters/vim-better-whitespace'
Plug 'schickling/vim-bufonly'
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
Plug 'Shougo/unite.vim'
Plug 'Shougo/vimfiler.vim'
Plug 'szw/vim-ctrlspace'
Plug 'tommcdo/vim-lion'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-endwise'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-speeddating'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-unimpaired'
Plug 'tpope/vim-vinegar'
Plug 'vim-scripts/gitignore'

" clojure things
Plug 'clojure-vim/async-clj-omni'
Plug 'clojure-vim/vim-jack-in'
Plug 'eraserhd/parinfer-rust', {'do': 'cargo build --release'}
Plug 'guns/vim-clojure-static'
Plug 'guns/vim-clojure-highlight'
Plug 'guns/vim-sexp'
Plug 'luochen1990/rainbow'
Plug 'radenling/vim-dispatch-neovim'
Plug 'SevereOverfl0w/vim-replant', { 'do': ':UpdateRemotePlugins' }
Plug 'snoe/clj-refactor.nvim', { 'do': ':UpdateRemotePlugins' }
Plug 'tpope/vim-classpath'
Plug 'tpope/vim-dispatch'
Plug 'tpope/vim-fireplace'
Plug 'tpope/vim-projectionist'
Plug 'tpope/vim-salve'
Plug 'tpope/vim-sexp-mappings-for-regular-people'

" other languages/filetypes
Plug 'adimit/prolog.vim'
Plug 'andreimaxim/vim-io'
Plug 'autozimu/LanguageClient-neovim', {
    \ 'branch': 'next',
    \ 'do': 'bash install.sh',
    \ }
Plug 'cespare/vim-toml'
Plug 'dag/vim-fish'
Plug 'dart-lang/dart-vim-plugin'
Plug 'daveyarwood/vim-alda'
Plug 'derekwyatt/vim-scala'
Plug 'digitaltoad/vim-pug'
Plug 'dleonard0/pony-vim-syntax'
Plug 'dpwright/vim-tup'
Plug 'elixir-lang/vim-elixir'
Plug 'fatih/vim-go'
Plug 'idris-hackers/idris-vim'
Plug 'jceb/vim-orgmode'
Plug 'jdonaldson/vaxe'
Plug 'jtratner/vim-flavored-markdown'
Plug 'JuliaEditorSupport/julia-vim'
Plug 'junegunn/vader.vim'
Plug 'kchmck/vim-coffee-script'
Plug 'keith/swift.vim'
Plug 'lambdatoast/elm.vim'
Plug 'leafgarland/typescript-vim'
Plug 'lfe/vim-lfe'
Plug 'l04m33/vlime', {'rtp': 'vim/'}
Plug 'mattn/emmet-vim'
Plug 'matze/vim-lilypond'
Plug 'mustache/vim-mustache-handlebars'
Plug 'OrangeT/vim-csharp'
Plug 'PProvost/vim-ps1'
Plug 'raichoo/purescript-vim'
Plug 'reasonml-editor/vim-reason-plus'
Plug 'rhysd/vim-crystal'
Plug 'rust-lang/rust.vim'
Plug 'stephencelis/vim-mml'
Plug 'tfnico/vim-gradle'
Plug 'tmux-plugins/vim-tmux'
Plug 'udalov/kotlin-vim'
Plug 'wlangstroth/vim-racket'
Plug 'zah/nim.vim'

" misc
Plug 'chrisbra/unicode.vim'
Plug 'eraserhd/git-zeal-vim'
Plug 'gregsexton/gitv'
Plug 'itchyny/calendar.vim'
Plug 'jreybert/vimagit'
Plug 'lambdalisue/gina.vim'
Plug 'mileszs/ack.vim'
Plug 'szw/vim-dict'
Plug 'terryma/vim-multiple-cursors'
Plug 'tpope/vim-eunuch'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-rhubarb'
Plug 'vimwiki/vimwiki'

call plug#end()

" ultimate vimrc stuff
set runtimepath+=~/.vim_runtime

source ~/.vim_runtime/vimrcs/basic.vim
source ~/.vim_runtime/vimrcs/filetypes.vim
source ~/.vim_runtime/vimrcs/plugins_config.vim
source ~/.vim_runtime/vimrcs/extended.vim

try
source ~/.vim_runtime/my_configs.vim
catch
endtry
