#!/usr/bin/env bash

clj_program=$(mktemp)

cat <<EOF > "$clj_program"
(require '[clojure.data   :as    data]
         '[clojure.pprint :refer (pprint)])

(let [[file-1 file-2] *command-line-args*]
  (->> [file-1 file-2]
       (pmap #(read-string (str "[\n" (slurp %) "\n]")))
       (apply data/diff)
       butlast
       pprint))

(System/exit 0)
EOF

clojure "$clj_program" "$@"
