#!/usr/bin/env bash

email="dave.yarwood@gmail.com"

if [[ "$(uname)" == Darwin ]]; then
  # HACK: This isn't really macOS specific, but this happens to be the email
  # that I want to use on my work laptop.
  email="david.yarwood@fieldguide.io"
fi

credential_section=""
gh_bin="$(command -v gh)"
if [[ -n "$gh_bin" ]]; then
  # GitHub CLI's token handles HTTPS git auth on GitHub (any platform, as long
  # as `gh auth login` has been run).
  credential_section="[credential \"https://github.com\"]
  helper = !$gh_bin auth git-credential
[credential \"https://gist.github.com\"]
  helper = !$gh_bin auth git-credential"
fi

cat <<EOF > "$HOME/.gitconfig"
# This gitconfig was generated via ~/.bin/generate-gitconfig.
# Edit that file, not this one!

[user]
  name = Dave Yarwood
  email = $email

[commit]
  gpgsign = true

$credential_section

[init]
  defaultBranch = main

[push]
  default = simple

[pull]
  rebase = true

[rerere]
  enabled = true

[core]
  autocrlf = input
  editor = nvim
  excludesfile = $HOME/.gitignore_global
  pager = delta

[interactive]
  diffFilter = delta --color-only
EOF
