#!/usr/bin/env bash

email="dave.yarwood@gmail.com"

if [[ "$(uname)" == Darwin ]]; then
  # HACK: This isn't really macOS specific, but this happens to be the email
  # that I want to use on my work laptop.
  email="david.yarwood@fieldguide.io"
fi

cat <<EOF > "$HOME/.gitconfig"
# This gitconfig was generated via ~/.bin/generate-gitconfig.
# Edit that file, not this one!

[user]
  name = Dave Yarwood
  email = $email

[commit]
  gpgsign = true

[init]
  defaultBranch = main

[push]
  default = simple

[pull]
  rebase = true

[rerere]
  enabled = true

[core]
  autocrlf = input
  editor = nvim
  excludesfile = $HOME/.gitignore_global
  pager = delta

[interactive]
  diffFilter = delta --color-only
EOF

# Credential helper, per-platform.
if [[ "$(uname)" == Darwin ]]; then
  git config --global credential.helper osxkeychain
else
  gh_bin="$(command -v gh)"
  if [[ -n "$gh_bin" ]]; then
    # Use GitHub CLI's token for HTTPS git auth on GitHub.
    git config --global 'credential.https://github.com.helper' "!$gh_bin auth git-credential"
    git config --global 'credential.https://gist.github.com.helper' "!$gh_bin auth git-credential"
  fi
fi
