#!/usr/bin/env bash

set -eo pipefail

while true; do
  if systemctl is-active --quiet jcagent.service; then
    touch /tmp/jumpcloud-is-active
  else
    rm -f /tmp/jumpcloud-is-active
  fi

  sleep 5
done

