#!/usr/bin/env bash

function log() {
  >&1 echo "$(date '+%Y-%m-%d %H:%M:%S') $*"
}

if ! nmcli dev | grep wifi | grep -q ' connected'; then
  log "Unable to check Alda API status. Wifi not connected."
  rm -f /tmp/alda-api-status
  exit 1
fi

results_dir="/tmp/alda-api-status-results"
mkdir -p "$results_dir"

status_code="$(curl -s \
                 -o /dev/null \
                 -w "%{http_code}" \
                 https://api.alda.io/releases/latest)"

if [[ -z "$status_code" ]]; then
  log "Something went wrong! Status code missing."
  exit 1
fi

echo "$status_code" > "$results_dir/$(date '+%Y%m%d%H%M%S')"

if [[ "$status_code" == "200" ]]; then
  printf '<span color="#00D000">Alda API up</span>' > /tmp/alda-api-status
else
  printf '<span color="#CC1616">Alda API down</span>' > /tmp/alda-api-status
fi

log "Successfully recorded Alda API response."
